import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {FunctionComponent} from "react";
import {LayoutProps} from "../next-types";
import {setStaticParamsLocale} from "next-international/server";
import {getStaticParams} from "@/locales/server";
import Providers from "./providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default (({params, children, }) => {
  setStaticParamsLocale(params.locale);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers locale={params.locale}>
          {children}
        </Providers>
      </body>
    </html>
  );
}) satisfies FunctionComponent<LayoutProps>;

export const generateStaticParams = getStaticParams;